### ISSUE TITLE
Violin with mean

### ISSUE THREAD

**Issue by yakir12** [JuliaPlots/StatsPlots.jl#127]
It would be nice to have an option of adding a mean/median line to the violin plots. These lines should be "halved" if `side` is not equal to `:both`.

**Comment by mkborregaard** [comment]
Could you give an example of how you'd like it to look?

**Comment by yakir12** [comment]
Sure! Something like this:
![lana](https://user-images.githubusercontent.com/3281957/35733502-f87f9d8a-081d-11e8-8440-cb7b443e136e.png)

**Comment by mkborregaard** [comment]
Yes looks good.
