### ISSUE TITLE
How to do a `groupbar` but sideways?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaPlots/StatsPlots.jl#129]
It's not clear if group at supports plotting the bar side ways. That is the same as `barh`.

**Comment by mkborregaard** [comment]
Could you try `orientation = :horizontal`?

**Comment by xiaodaigh** [comment]
OK I checked. It's working but with errors. IN particular the x and y axis labels are not correct e.g.

```julia
groupedbar(
    ["a","a","b"],
    [1,2,3],
    groups = [1,2,1],
    orientation = :horizontal
)
````

**Comment by mkborregaard** [comment]
on which backend?
