### ISSUE TITLE
grouped bar plots

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlots/StatsPlots.jl#13]
``` julia
using StatPlots
groupedbar(rand(10,3), bar_position = :stack, bar_width=0.7, alpha=0.5)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/18962081/58a2a5e0-863d-11e6-8638-94f88ecc544d.png)

This is the default:

``` julia
using StatPlots
groupedbar(rand(10,3), bar_position = :dodge, bar_width=0.7, alpha=0.5)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/18962092/673f6c78-863d-11e6-9ee9-8ca104e5d2a3.png)

**Comment by ChrisRackauckas** [comment]
That was quick.

**Comment by tbreloff** [comment]
I just have to decide to work on it...

**Comment by musm** [comment]
Thanks, FWIW this doesn't render properly using the glvisualizebackend

![image](https://cloud.githubusercontent.com/assets/4319522/18969042/7e08a0fc-8659-11e6-9608-bb6ed41ce21d.png)
