### ISSUE TITLE
@df df begin ... end no longer works

### ISSUE THREAD

**Issue by cstjean** [JuliaPlots/StatsPlots.jl#134]
The latest (0.7.1) release caused a new issue with the `@df` macro

```julia
julia> using Plots, StatPlots, DataFrames

julia> @df DataFrame(x=[1,2], y=[3,4]) begin
       end

julia> @df DataFrame(x=[1,2], y=[3,4]) begin
           plot(:x, :y)
       end
ERROR: StackOverflowError:
```

This used to work, and was convenient for doing multiple plots.

**Comment by piever** [comment]
Thanks for finding this! I somehow introduced some circularity in the macro expansion, should be fixable quickly.

One unrelated thing: as `@df` adds the expression you feed inside the plotting call, if you don't use a variable name but an expression that needs to be computed, to be sure it's not computed multiple times, you should be using piping:

```julia
julia> DataFrame(x=[1,2], y=[3,4]) |> @df  begin
           plot(:x, :y)
       end
```

I'll see if this can also be fixed easily or whether we should simply recommend the piping version.

**Comment by piever** [comment]
Can you try the fix at #135 as see if it works for you?

**Comment by cstjean** [comment]
Will do on Monday. If you tested it on the example above and it works, I assume it's fine...

**Comment by piever** [comment]
Merged and tagged a new release.
