### ISSUE TITLE
Remove dependency on Plots.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/StatsPlots.jl#138]
What is the part of the code that currently depends on Plots.jl? Could it be purged out or refactored?

I opened an issue a while ago arguing that this package could be split into many smaller packages, and I still think that this argument holds today :+1:

**Comment by mkborregaard** [comment]
I disagree. On the contrary, I think this whole package could be merged into Plots.jl proper. The original purpose of splitting it out was to avoid the heavy dependency of DataFrames, but it no longer has that, and `Missing` support is moving to Base in 0.7.
For the record, it was PlotRecipes, not StatPlots that you suggested splitting. I still think, as stated here https://github.com/JuliaPlots/PlotRecipes.jl/issues/32#issuecomment-322065222 that it would make sense to split the Graph recipes off in their own package, but keep the rest together.

**Comment by juliohm** [comment]
Thank you for sharing. I will rewrite some of the recipes myself on my packages, cannot afford such big dependency at the moment.

**Comment by piever** [comment]
Could you check if you can circumvent this by using Requires and returning for example the`GroupedBar` type in your recipes?

**Comment by piever** [comment]
What I proposed was to have a small package containing only the type definitions for type recipes, which would be a developer target, Plots would then implement the actual recipe. In this way you don't increase your package load time but your recipes would work when the user also loads Plots, which they have to anyway.

**Comment by juliohm** [comment]
Sorry, I misunderstood it :) You mean a package just exporting the names of the recipes without the actual implementation?

**Comment by piever** [comment]
No problem :) Yes, that's the idea. I think currently mainly type recipes are problematic and as they are implemented by overloading some functions, the overloading can happen in a separate package who would have all the necessary dependencies but the type definition would be in the small dependency free package (it's type piracy but I don't think that would be an issue in this case as long as the rules are clear).

There is an other possible strategy. AFAIU to use `groupedbar` in your recipes you basically need to return a `GroupedBar` object. Could you simply use Requires.jl and wrap your recipe in a `@require StatPlots`block and then in that block you can return `StatPlots.GroupedBar` objects? In this way that code would only be loaded when the user does:

```julia
using StatPlots, YourPackage
```

If this works, maybe that's also an acceptable solution.

I'll leave the issue open as making type recipes available without depending on the package is an important unresolved issue.

**Comment by juliohm** [comment]
The idea is very clever, but I think it is also convoluted for the goals we are trying to achieve as developers. It is like addressing the issue of not having a modular recipe ecosystem via compilation with Requires.jl and other Julia tricks that are not necessarily elegant.

Thanks for re-opening the issue, I appreciate the feedback :+1:

**Comment by mkborregaard** [comment]
Hi @piever , the `@require` trick works, e.g.
```
module Test
using RecipesBase, Requires

struct MyType end
export MyType


@require StatPlots begin
    @recipe f(t::MyType) = StatPlots.GroupedBar((rand(10,3),))
end
end

using Test, StatPlots
plot(MyType())
```
I like it. 
But your idea of defining stub dispatch types in a dependency-free package is even nicer. Do we need a package for it, do you think? Or should we allow them to live along the `@shorthands` and `@userplot` macros in RecipesBase?

**Comment by mkborregaard** [comment]
BTW @juliohm it is your idea of atomizing this package I don't agree with. I do think it could be a good idea to drop the Plots dep, and it shouldn't be difficult. I see that is also the title of the post.

But I find your idea of breaking this package to pieces absurd. Your statement that it "goes against the Julia philosophy in general" is unfair. And so is your claim that we have an "idea of merging everything on a single package". The package is dependency-light (except possibly Plots, but Plots is also really dependency-light in fact), is only around 1000 lines of code, and it only defines like 7-8 well-formed functions that make a natural unit.

But as I said, we could talk about dropping the Plots dep.

**Comment by piever** [comment]
@mkborregaard I agree with you that we can simply add them to RecipesBase, I'll make the PRs in the next few days. One more thing: can I take advantage of this reorganization to also move `group_as_matrix` from Plots to RecipesBase? In this way we would allow packages to make full use of the recipes system without depending on Plots.

**Comment by mkborregaard** [comment]
I wonder if there's some way to build in a nice error message ("You need to load StatPlots to use this recipe") in the macros?

**Comment by mkborregaard** [comment]
This should be resolved now - there's now a functionality to end any recipe with `recipetype(:groupedbar, my_args)` that will dispatch to GroupedBar if StatsPlots is loaded. This means a dependency on this package is no longer needed.
