### ISSUE TITLE
How to plot legend upside down in stacked groupedbar

### ISSUE THREAD

**Issue by ngphuoc** [JuliaPlots/StatsPlots.jl#140]
It's is easier to see the legend and the stacked bars colors having the same order. Especially when there are many groups.

**Comment by mkborregaard** [comment]
Yes, they should be the same color for sure. You can't specify it, but it should be built in.

**Comment by Lilyhanig** [comment]
The problem is that the order is reverse to the way it get's stacked, they're listed top down, when generally bottom up is preferred for stacked bars.

**Comment by mkborregaard** [comment]
Yes exactly. The order of colors in the bars should be reversed. It's a really nice first PR if anyone is interested.

**Comment by mkborregaard** [comment]
Closed in #309
