### ISSUE TITLE
ERROR: LoadError: MethodError: all(::Reexport.##2#6, ::Array{Any,1}) is ambiguous.

### ISSUE THREAD

**Issue by NHDaly** [JuliaPlots/StatsPlots.jl#146]
I'm not sure if this is a bug in `StatPlots`, in `Plots` or in `julia`, but I'm seeing the following error when I try to run `using StatPlots` after `workspace()`:

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> using Plots

julia> using StatPlots

julia> workspace()

julia> using Plots
WARNING: Method definition (::Type{DomainError})(Any) in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:503 overwritten in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:503.
WARNING: Method definition (::Type{DomainError})(Any, Any) in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:504 overwritten in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:504.
WARNING: Method definition (::Type{OverflowError})(Any) in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:509 overwritten in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:509.
WARNING: Method definition (::Type{InexactError})(Symbol, Any, Any) in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:498 overwritten in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:498.
WARNING: Method definition (::Type{Main.Base.IOContext{IO_t} where IO_t<:IO})(Main.Base.IOContext{IO_t} where IO_t<:IO, Main.Base.Pair{A, B} where B where A, Main.Base.Pair{A, B} where B where A) in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:1003 overwritten in module Compat at /Users/daly/.julia/v0.6/Compat/src/Compat.jl:1003.

[... skipping tons of warnings ...]

WARNING: Method definition convert(Type{Array{T<:Real, 1}}, Main.Base.Range{T<:Real}) in module Plots at /Users/daly/.julia/v0.6/Plots/src/utils.jl:450 overwritten in module Plots at /Users/daly/.julia/v0.6/Plots/src/utils.jl:450.
WARNING: Method definition convert(Type{Array{T<:Real, 1}}, Main.Base.Range{S<:Real}) in module Plots at /Users/daly/.julia/v0.6/Plots/src/utils.jl:451 overwritten in module Plots at /Users/daly/.julia/v0.6/Plots/src/utils.jl:451.

julia> using StatPlots
ERROR: LoadError: MethodError: all(::Reexport.##2#6, ::Array{Any,1}) is ambiguous. Candidates:
  all(f, A::AbstractArray{#s18,N} where N where #s18>:Missings.Missing) in Missings at /Users/daly/.julia/v0.6/Missings/src/Missings.jl:190
  all(f, A::AbstractArray{#s18,N} where N where #s18>:LastMain.Missings.Missing) in LastMain.Missings at /Users/daly/.julia/v0.6/Missings/src/Missings.jl:190
Possible fix, define
  all(::Any, ::AbstractArray{#s18,N} where N where #s18>:Union{LastMain.Missings.Missing, Missings.Missing})
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] eval(::Module, ::Any) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [3] _require(::Symbol) at ./loading.jl:490
 [4] require(::Symbol) at ./loading.jl:405
while loading /Users/daly/.julia/v0.6/StatPlots/src/StatPlots.jl, in expression starting on line 5

julia>
```

The minimum example where I was able to reproduce the error was running:
`julia> using Plots; workspace(); using Plots; using StatPlots`

I did not see the error when running:
`julia> using Plots; using StatPlots; workspace(); using StatPlots`
`julia> workspace(); using Plots; using StatPlots`
`julia> using Plots; using StatPlots; workspace(); using Plots`

----------

It looks like this has something to do with `Reexport`?

**Comment by mkborregaard** [comment]
Most likely. I think `workspace` has been dropped from julia 0.7, right?

**Comment by NHDaly** [comment]
Oh, really? I wasn't aware. I've sadly been not keeping up very well on 0.7 development...

Is the answer then just not to use `workspace()`?

I had hoped that we'd fixed our code by just removing the `using Plots` line from our code, and only having `using Statplots` (like i mentioned in the "working" cases above) however, it actually still fails after the second `workspace()` call. 😢

**Comment by NHDaly** [comment]
It would be ideal if we could find why this is happening and fix it. Should I open this issue on Reexport instead?

**Comment by nico202** [comment]
@NHDaly I didn't know, too. Reading on some issues, it seems that while developing modules it's just beeter to user Revise.jl. And to reload an external module reload(::Module) will be/has been added (instead of reload(module::String)).

**Comment by NHDaly** [comment]
😢 So, at least for now, we're not using Modules at all. All our code is just organized as scripts.

(Our engineer is coming from matlab, and so I wanted to keep the code as simple and similar to matlab as possible, at least for now.)

So I'll try posting an issue on Reexport.jl to see if I can get this specific problem fixed. Thanks.

**Comment by miguelmorin** [comment]
The `Revise` solution by @ararslan in the [Reexport issue](https://github.com/simonster/Reexport.jl/issues/14) works well. This is not specific to `Reexport` or `StatsPlots`. I added an answer [here](https://stackoverflow.com/questions/25028873/how-do-i-reload-a-module-in-an-active-julia-session-after-an-edit/50816280#50816280).

**Comment by mkborregaard** [comment]
Great.
