### ISSUE TITLE
accessing columns with names containing dots is unwieldy

### ISSUE THREAD

**Issue by sschelm** [JuliaPlots/StatsPlots.jl#177]
Using the `@df` macro to plot dataframes with columns containing names with dots, currently requires the use of `cols(Symbol("my.column"))`.

This seems rather unwieldy (just using `Symbol()` is not enough).
I think a shorter and quicker way may be helpful.

I thought backticks once worked  to escape this case.

**Comment by mkborregaard** [comment]
:scream: column names with dots?!

**Comment by sschelm** [comment]
Yeah, I know.
Not my choice, I try to avoid that.

But I think that might actually be not uncommon, especially with legacy datasets.

**Comment by piever** [comment]
I agree that the dots are a really bad choice, esp. given dot overloading: eg. `df.my.column` , but maybe `cols` could also accept strings and then `cols("my.column")` would work...

**Comment by mkborregaard** [comment]
👍 That's a good idea IMHO

**Comment by mkborregaard** [comment]
This should be fixed in DataFrames
