### ISSUE TITLE
density with weights

### ISSUE THREAD

**Issue by Nosferican** [JuliaPlots/StatsPlots.jl#201]
Consider
```
using StatsBase, StatPlots
density(1:3) # Fine
density(1:3, weights = weights([0,500,1])) # No change
density(1:3, weights = [0,500,1]) # No change
density(vcat(1, ones(500), 2)) # Correct
density(1:3, weights([0,500,1])) # Not sure what this is
```

**Comment by mkborregaard** [comment]
Hi, when opening issues, could you please post runnable code (including all `using`s) and post the plot if it's the plot that is the concern here?
Here's an MWE and a plot based on this:
```julia
using StatsBase, StatPlots
plot(
       density(1:3), # Fine
       density(1:3, weights = weights([0,500,1])), # No change
       density(1:3, weights = [0,500,1]), # No change
       density(vcat(1, ones(500), 2)), # Correct
       density(1:3, weights([0,500,1])), # Not sure what this is
legend = false) 
```
<img width="582" alt="skaermbillede 2018-11-26 kl 08 57 40" src="https://user-images.githubusercontent.com/8429802/49000283-5c6f9500-f159-11e8-9def-2329bc6b515d.png">

So, your concern is that the `weights` argument to density appears to be ignored by StatPlots?

**Comment by Nosferican** [comment]
Will do. That is correct.

**Comment by cossio** [comment]
> So, your concern is that the weights argument to density appears to be ignored by StatPlots?

Yes, I'm having the same issue and would definitely like to have a usable `weights` keyword on `density` with the same function as the `weights` option in `histogram`.

**Comment by mkborregaard** [comment]
StatsPlots uses KernelDensity.kde for the density plots. Though I can see a way of hacking support for weights directly here, a more sustainable option might be to request this on KernelDensity? Happy to forward the support here if they add it there.

**Comment by Nosferican** [comment]
Just to verify before opening an issue with KernelDensity, the following feature doesn't give you what you would need to adapt the code here? https://github.com/JuliaStats/KernelDensity.jl/pull/26 It was the only issue/PR I found regarding weights in KernelDensity.

**Comment by mkborregaard** [comment]
Oh I see it does work, just wasn't documented (where I looked)! Let me have a look.

**Comment by Nosferican** [comment]
Perfect! It would still be good to open an issue there to have it documented if that is still the case.

**Comment by mkborregaard** [comment]
Does this give what you'd expect @Nosferican ? https://github.com/JuliaPlots/StatsPlots.jl/pull/232

<img width="590" alt="Skærmbillede 2019-05-27 kl  19 38 13" src="https://user-images.githubusercontent.com/8429802/58433366-377fbe80-80b7-11e9-938c-65ed41e94e04.png">

**Comment by Nosferican** [comment]
I think for the first four plots it is what I would expect. 💯I am not sure about the last one. From the documentation, I don't know what would `density(::AbstractVector, ::AbstractVector)` or `density(::AbstractVector, ::Weights)` should do. Whatever it is currently doing, is beyond me. 🤷‍♂Maybe that one should give a `MethodError`. Alternatively,
```
density(x::AbstractVector, wts::Weights) = density(x, weights = wts)
```
would make sense and would be what I would argue for as an improvement over current behavior.

**Comment by mkborregaard** [comment]
I'd argued for keeping it as is on the PR

**Comment by Nosferican** [comment]
Thanks for the PR!
