### ISSUE TITLE
Rename package to StatsPlots?

### ISSUE THREAD

**Issue by nalimilan** [JuliaPlots/StatsPlots.jl#205]
As discussed at https://github.com/JuliaStats/StatsKit.jl/issues/5#issuecomment-416582593, we have now StatsKit, StatsBase, StatsModels, StatsFuns and StatsMakie (plus the JuliaStats organization). How do you feel about renaming this package to StatsPlots for consistency? That would be annoying for users, but better do this sooner than later.

**Comment by mkborregaard** [comment]
Yes, we've already agreed to that - all we need is to work out how to it. Simple solution: rename the repo and announce it on discourse. Will render every single tutorial out there relying on StatPlots fail. @piever ?

**Comment by nalimilan** [comment]
Cool. One question is what to do with the existing package. If we keep it around, people won't notice it has been renamed and will keep using the current version forever. Or maybe tag a final version which will print "Package has been renamed to StatsPlots" when trying to load it?

**Comment by mkborregaard** [comment]
No we can simply rename this package, so nothing old will be hanging around. I do believe that with the new METADATA system it will update automatically, given that in that packages are defined by their uuid, not their name - which is the reason I've been waiting to do this.

**Comment by mkborregaard** [comment]
@daschw OK we agree here and I've already merged the warning that the name StatPlots is deprecated and pushed a new release. However my privs don't extend to changing the name of the repo - would you mind changing it to StatsPlots.jl , then I'll do the rest?
Thanks.

**Comment by piever** [comment]
If we change the name here, will StatPlots still install on Julia 0.6?

**Comment by daschw** [comment]
I renamed it to StatsPlots.jl.

**Comment by mkborregaard** [comment]
Done.

**Comment by nalimilan** [comment]
I've just noticed there are occurrences in the Plots.jl manual too.

**Comment by mkborregaard** [comment]
Fixed.
