### ISSUE TITLE
Don't fix now: Eventually unregister StatPlots (when 0.6 is completely out of use)

### ISSUE THREAD

**Issue by cossio** [JuliaPlots/StatsPlots.jl#225]
Is it possible to "unregister" `StatPlots`? Everytime I have to install the package I get confused about whether I should install `StatPlots` or `StatsPlots`.

**Comment by mkborregaard** [comment]
It's necessary for julia 0.6 and earlier though.

**Comment by piever** [comment]
I think it's a bad idea to unregister it, we would break things for a lot of people (all 0.6 users for example).

**Comment by cossio** [comment]
Does this mean that `StatPlots` will be lying around on the registry forever? Perhaps a better solution is to unregister it, just not right now.

**Comment by mkborregaard** [comment]
Yes I guess it should be eventually

**Comment by cossio** [comment]
@mkborregaard Until then keep this open?

**Comment by coroa** [comment]
Well, you could have it removed from the [General registry](https://github.com/JuliaRegistries/General/tree/master/S/StatPlots) without impacting pre-0.7 Julia, since the sync with METADATA has been disabled! I suppose. Don't think there is an agreed procedure on how-to and don't know who to ping about that, though!

**Comment by mkborregaard** [comment]
That's a good point - @piever should we remove StatPlots from GENERAL?

**Comment by piever** [comment]
Maybe better to check with Pkg and registry devs first. Somehow I suspect this is a bit against the spirit of releases: i.e. if some app had a Manifest indicating some version of StatPlots, we would break it (whereas the whole point of having a Manifest was to work reliably).

**Comment by DilumAluthge** [comment]
FYI - I have merged https://github.com/JuliaRegistries/General/pull/39292, so I think that this can be closed now?
