### ISSUE TITLE
Simple horizontal confidence interval

### ISSUE THREAD

**Issue by PharmCat** [JuliaPlots/StatsPlots.jl#242]
How to draw simple confidence interval (horizontal)?

How to draw forest CI like this: [https://a-little-book-of-r-for-biomedical-statistics.readthedocs.io/en/latest/_images/image2.png](url)

**Comment by nilshg** [comment]
This maybe should be a Discourse post rather than an issue? Have you looked at: https://discourse.julialang.org/t/how-to-plot-mean-deviation-in-plots-jl/1975/4

**Comment by PharmCat** [comment]
Hi! This issue is a quastion and issue itself. I found no method to visualize confidence interval. Not on graphic with data. For example - I have mean, lower bound, upper bound i'd like to get picture of this confidence interval. Or i have many CI and i have to make forest plot. It will be nice if i could make it with StatPlots.jl

**Comment by mkborregaard** [comment]
`xerror` attribute. Look in https://docs.juliaplots.org/latest/attributes/

**Comment by PharmCat** [comment]
Sorry, how can i make this:
![image2](https://user-images.githubusercontent.com/13901158/60596935-a802b500-9db2-11e9-800f-cc08f937a21a.png)
with xerror?

**Comment by daschw** [comment]
```julia
julia> x = 1:3
1:3

julia> y = 4:6
4:6

julia> xerror = collect(zip(rand(3), rand(3)))
3-element Array{Tuple{Float64,Float64},1}:
 (0.39655114729088026, 0.10912407894921783)
 (0.20562413451454464, 0.34170340718394243)
 (0.4180474544349393, 0.1352904554473151)

julia> scatter(x, y, xerror = xerror)
```
![xerror](https://user-images.githubusercontent.com/16589944/60597528-5e629c00-9dab-11e9-9c0a-9db23f5ab682.png)

You can also just pass a vector to xerror to have symmetric errorbars.

**Comment by PharmCat** [comment]
Thank you so much!
