### ISSUE TITLE
Horizontal boxplot

### ISSUE THREAD

**Issue by iblis17** [JuliaPlots/StatsPlots.jl#251]
Seems this is not supported yet.
And I found there is an option `vert = false` in PyPlot's `boxplot`.

**Comment by logankilpatrick** [comment]
Can you elaborate more on what you are asking for?

**Comment by iblis17** [comment]
Hi @logankilpatrick 
I want something like this:
http://www.r-tutor.com/elementary-statistics/numerical-measures/box-plot

**Comment by AlexanderVanUffelen** [comment]
There is an attribute 'orientation'.
For example a barplot can be made horizontal
`bar(["One","Two","Three"], [1,2,3], orientation=:h)`
![bar](https://user-images.githubusercontent.com/49979885/108849376-5e4b8b80-75e2-11eb-9e4e-b9fd9385cca8.png)
But when trying to do the same with a boxplot, it doesn't plot the boxplot:
`boxplot(["One"], [1,2,3], orientation=:h)`
![boxplot](https://user-images.githubusercontent.com/49979885/108849573-9357de00-75e2-11eb-8842-32c62c993f69.png)
The vertical one works just fine:
`boxplot(["One"], [1,2,3], orientation=:v)`
![boxplot_vert](https://user-images.githubusercontent.com/49979885/108849632-acf92580-75e2-11eb-8ed8-32990460f02b.png)

Is this a bug or am I doing something wrong?

**Comment by SiFTW** [comment]
This is still an issue and affects horizontal stacked bar plots too.
