### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/StatsPlots.jl#254]
Would it be time to release a new version?

**Comment by daschw** [comment]
Sure.

**Comment by mkborregaard** [comment]
I concur :joy:

**Comment by daschw** [comment]
https://github.com/JuliaRegistries/General/pull/5595

**Comment by asinghvi17** [comment]
Should we update the pull request, since I just merged #265?  It needs some upper bounds for compatibility anyway.
