### ISSUE TITLE
Log-scale groupedbar at different height positions.

### ISSUE THREAD

**Issue by sairus7** [JuliaPlots/StatsPlots.jl#263]
```
ctg = repeat(["Category 1", "Category 2"], inner = 5)
nam = repeat("G" .* string.(1:5), outer = 2)

v = 100*rand(5, 2)
groupedbar(nam, v, group = ctg, xlabel = "Groups", ylabel = "Scores",
        title = "Scores by group and category", bar_width = 0.67,
        lw = 0, framestyle = :box, yaxis=:log)
```

Produces the following plot:
![image](https://user-images.githubusercontent.com/20798349/67221489-35d2e080-f434-11e9-84c1-a62fa2c332d0.png)

**Comment by Moelf** [comment]
any updates, I'm seeing the same bug, does this only happen in log scale?

**Comment by joergbuchwald** [comment]
I'm same the same bug too. Is there any workaround while it's not fixed?

**Comment by Moelf** [comment]
actually I think this bug is partially fixed but there might be a different but now, can you post a MWE?

**Comment by joergbuchwald** [comment]
`ctg = repeat(["A", "B", "C" ], outer = 2)
nam = repeat(["small", "aniso_small"], inner = 3)
data=[10 12; 1 1; 0.25 0.25]
groupedbar(nam, data, group = ctg, xlabel = "size", yaxis=:log, legendfontsize = 11, tickfont = (11, :black),  ylabel = "speed-up", bar_width = 0.37,
        lw = 0, framestyle = :box)`
[test_logscale.pdf](https://github.com/JuliaPlots/StatsPlots.jl/files/4848613/test_logscale.pdf)

**Comment by Moelf** [comment]
well, on `#master` your command doesn't work unless given `ylims=(0.1, 1e3)` or something, and then I see this 
![image](https://user-images.githubusercontent.com/5306213/86074554-36585800-ba54-11ea-9527-a3cf061386c4.png)

which is almost right except the top is too high (goes to infinity). What I want to know is what's the real-world application for this since I fixed this last time in #349

**Comment by Moelf** [comment]
actually, it works now?

![image](https://user-images.githubusercontent.com/5306213/86076165-a0bec780-ba57-11ea-9d8d-78ca1fcb6d18.png)

**Comment by Moelf** [comment]
after that PR:
```
groupedbar(nam, data, group=ctg, yscale=:log, xlabel = "size",  ylabel = "speed-up", bar_width = 0.37, lw = 0, framestyle = :box)
```
![image](https://user-images.githubusercontent.com/5306213/86080194-4aa25200-ba60-11ea-8088-ac505c38c3bd.png)

```
groupedbar(nam, data, group=ctg, yscale=:log, xlabel = "size",  ylabel = "speed-up", bar_width = 0.37, lw = 0, framestyle = :box, ylims=(1e-2, Inf))
```
![image](https://user-images.githubusercontent.com/5306213/86080209-5aba3180-ba60-11ea-90a5-f26688d861a6.png)

and original MWE by @sairus7:

![image](https://user-images.githubusercontent.com/5306213/86080228-6d346b00-ba60-11ea-856b-ac962a9a3eb4.png)

**Comment by joergbuchwald** [comment]
> actually, it works now if you give it `fillrange`? can you try master branch?
> 
> ![image](https://user-images.githubusercontent.com/5306213/86076165-a0bec780-ba57-11ea-9d8d-78ca1fcb6d18.png)
> 
> ```
> julia> data=[10 12; 1 1; 0.25 0.25]
> 3×2 Array{Float64,2}:
>  10.0   12.0
>   1.0    1.0
>   0.25   0.25
> 
> julia> nam = repeat(["small", "aniso_small"], inner = 3)
> 6-element Array{String,1}:
>  "small"
>  "small"
>  "small"
>  "aniso_small"
>  "aniso_small"
>  "aniso_small"
> 
> julia> ctg = repeat(["A", "B", "C" ], outer = 2)
> 6-element Array{String,1}:
>  "A"
>  "B"
>  "C"
>  "A"
>  "B"
>  "C"
> 
> julia> groupedbar(nam, data, group=ctg, yscale=:log, xlabel = "size",  ylabel = "speed-up", ylims=(0.1,1000), bar_width = 0.37, lw = 0, framestyle = :box, fillrange=1e-2)
> ```

This looks good. Thank you very much indeed!
