### ISSUE TITLE
Showing Probability Mass Function for discrete distributions

### ISSUE THREAD

**Issue by alecloudenback** [JuliaPlots/StatsPlots.jl#287]
For [discrete distriubtions](https://juliastats.org/Distributions.jl/stable/univariate/#Discrete-Distributions-1), it would be nice to have a way to plot the [pmf](https://en.wikipedia.org/wiki/Probability_mass_function).

Currently, when trying to plot a discrete distribution, it shows a line plot with the two points connected. E.g.:

`plot(Bernoulli(0.1))`:
![image](https://user-images.githubusercontent.com/711879/71049362-b9910c80-2107-11ea-9741-6e375cffb32e.png)

**Comment by mkborregaard** [comment]
Agreed, that would be nice. You'd expect this to show a histogram?

**Comment by alecloudenback** [comment]
I think a [hairplot](https://gadflyjl.org/stable/gallery/geometries/#[Geom.hair](@ref)-1) nicely conveys the discreteness of outcomes, whereas a histogram can imply that their is a spread of values within the visual width (bin) of the bar.

Wikipedia also uses a hairplot in its example of a probability mass function.

**Comment by mkborregaard** [comment]
Makes sense. That's `seriestype = :sticks` in Plots.
