### ISSUE TITLE
Boxplot bar_width has no effect

### ISSUE THREAD

**Issue by HenriDeh** [JuliaPlots/StatsPlots.jl#292]
When I boxplot without given x as input, the box is fat, its width matches that of the plot itself. I'm trying to make it thiner, I looked in the source code and it appears that bar_width should be the relevant attribute. It does not work.

mwe:

`plot(rand(100), seriestype = :boxplot, bar_width = 0.1)`

**Comment by mkborregaard** [comment]
Your mwe literally does not have `bar_width` in it :joy:

**Comment by HenriDeh** [comment]
There you go

**Comment by mkborregaard** [comment]
That works for me - but may be hard to see for you as you only have a single box:
```julia
plot(rand(1:2, 100), rand(100), seriestype = :boxplot, bar_width = 0.1)
```
![Skærmbillede 2020-01-29 kl  13 24 28](https://user-images.githubusercontent.com/8429802/73356458-b5294900-429a-11ea-87e3-832a42f6a395.png)

```julia
plot(rand(1:2, 100), rand(100), seriestype = :boxplot, bar_width = 0.4)
```
![Skærmbillede 2020-01-29 kl  13 24 18](https://user-images.githubusercontent.com/8429802/73356464-b9edfd00-429a-11ea-9397-be9d28b4741a.png)

**Comment by HenriDeh** [comment]
So it's the plot that I have to resize?
________________________________

**Comment by mkborregaard** [comment]
If you only have a single bar, you can change the `xlims`

**Comment by HenriDeh** [comment]
Okay that worked. Thank you.
