### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devmotion** [JuliaPlots/StatsPlots.jl#303]
Is it possible to release a new version? As https://github.com/JuliaPlots/StatsPlots.jl/issues/301 shows, if Pkg installs Tables >= 1 before adding StatsPlots, users end up with StatsPlots 0.12 that does not upper bound its dependencies but actually is incompatible with Tables >= 1.

**Comment by kescobo** [comment]
Yes please - I'm having a similar problems.

**Comment by asinghvi17** [comment]
does it work with 1.0?  @kescobo

**Comment by kescobo** [comment]
@asinghvi17 Not sure, I'm blocked from upgrading by explicit version bounds 🤦‍♂. I haven't tested - TBH I'm not sure how Tables is integrated

**Comment by asinghvi17** [comment]
@devmotion we might have to fix this in the registry as well.

**Comment by kalmarek** [comment]
is there a way of getting a working `@df` macro right now??

**Comment by asinghvi17** [comment]
Does it not work? If so, could you open another issue with the error?

**Comment by kalmarek** [comment]
I get the same error as in #301which is already fixed on master, but I'd rather not install it as it (or seems to) requires dev verstion of Plots, etc. So the question is rather:
how do I workaround, so that I can an environment which can run the examples from readme.

**Comment by kalmarek** [comment]
```julia
using Pkg
Pkg.rm("DataFrames")
Pkg.rm("StatsPlots")
pkg"add Tables@0.2"
Pkg.add("DataFrames")
Pkg.add("StatsPlots")
```
seems to have fixed this in my case, sorry for the noise.
