### ISSUE TITLE
Grouped Boxplot Labels Missing Items

### ISSUE THREAD

**Issue by zacharyneveu** [JuliaPlots/StatsPlots.jl#318]
When I use a grouped boxplot, the number of legend items is not the same as the number of groups. The labels themselves seem right, but there are several items missing. In the example below, there should be a third label for "Spot 3", however this is missing.

![box2](https://user-images.githubusercontent.com/23347363/77187979-af3a3200-6aab-11ea-9f39-430a78fe72cc.png)

**Comment by zacharyneveu** [comment]
Update: It appears to be a `pgfplots` issue, looks fine with `gr`. Should this be moved to the `pgfplots` repo then?

![box2](https://user-images.githubusercontent.com/23347363/77188526-84041280-6aac-11ea-9d0d-ba9a1dc14630.png)

**Comment by daschw** [comment]
> Should this be moved to the pgfplots repo then?

No, that's an issue with `pgfplots` backend code in Plots.jl and not in PGFPlots.jl
