### ISSUE TITLE
groupedbar with error bars not working with plotlyjs

### ISSUE THREAD

**Issue by piever** [JuliaPlots/StatsPlots.jl#32]
The plotlyjs backend doesn't handle the groupedbar recipe with error bars correctly:

<img width="515" alt="screenshot 2016-12-19 14 21 32" src="https://cloud.githubusercontent.com/assets/6333339/21315996/ac612654-c5f6-11e6-8fd1-ac90ef44fc1e.png">

gr instead produces the expected outcome:

<img width="500" alt="screenshot 2016-12-19 14 21 53" src="https://cloud.githubusercontent.com/assets/6333339/21316006/b747258c-c5f6-11e6-9788-7ea911600033.png">

**Comment by mkborregaard** [comment]
I think there is a general issue with shapes on plotlyjs()

**Comment by tbreloff** [comment]
Yes it's a miracle I got shapes to work at all with plotly... Such bad
support.

**Comment by piever** [comment]
Actually in this case what happens is that the some of the series in the plot (the path series used for the errorbars) also get the fillrange parameter, so the random filling come from those. Is there an easy way to change the groupedbar recipe so that the fillrange is set to zero only for bar series and not for path series?

**Comment by piever** [comment]
Fixed by #30
