### ISSUE TITLE
groupedbar @df group syntax doesn't work for `Date`s

### ISSUE THREAD

**Issue by Moelf** [JuliaPlots/StatsPlots.jl#341]
can we support this `@df df groupedbar(:x, y:, group=:z)`?

since the same works for `groupedhist` already

**Comment by mkborregaard** [comment]
It's a bug if that does not work

**Comment by Moelf** [comment]
```
using StatsPlots
d = DataFrame(x=[1,2,3,4], y = [2,2,4,4], g=["a", "a", "b", "b"])
@df d groupedbar(:x, :y, group=:g)
```
![image](https://user-images.githubusercontent.com/5306213/83110138-77390780-a077-11ea-813d-5017febb54d9.png)

**Comment by daschw** [comment]
Seems to work fine for me:
```julia
using StatsPlots, DataFrames
df = DataFrame(
    x = repeat(['A', 'B'], outer = 3),
    y = 1:6,
    z = repeat(1:3, inner = 2),
)
@df df groupedbar(:x, :y, group = :z)
```
![groupedbar](https://user-images.githubusercontent.com/16589944/83110372-4383cf00-a0c3-11ea-8980-2ce158e2e8f7.png)

**Comment by Moelf** [comment]
ah, I realized the bug is actually from it unable to handle `Date`,
```
d = DataFrame(
x=[DateTime(2020, 3,1), DateTime(2020, 3,2), DateTime(2020, 3,1), DateTime(2020, 3,2)], 
    y = [2,2,4,4], g=["a", "a", "b", "b"])
@df d groupedbar(:x, :y, group=:g, bar_position=:stack)
```
