### ISSUE TITLE
groupedbar() undesired stacking

### ISSUE THREAD

**Issue by yookiwooki** [JuliaPlots/StatsPlots.jl#355]
I'm working on the master branch, and I'm finding undesired stacking.  I'm seeing this output with the groupedbar() example from the Readme.  Since I'm using rand() there shouldn't be any values above 1.  Anybody else seeing this?

```julia
ctg = repeat(["Category 1", "Category 2"], inner = 5)
nam = repeat("G" .* string.(1:5), outer = 2)

groupedbar(nam, rand(5, 2), group = ctg, xlabel = "Groups", ylabel = "Scores",
        title = "Scores by group and category", bar_width = 0.67,
        lw = 0, framestyle = :box)
```
<img width="401" alt="Capture" src="https://user-images.githubusercontent.com/33902914/87463408-f1e1c600-c5d6-11ea-9dba-bf9e71f26855.PNG">

**Comment by SteffenPL** [comment]
This might be related... In my example with `groupedhist`.

I don't even see the relationship between the combined plot and the single ones...

```julia
using DataFrames, Random, StatsPlots, Query
Random.seed!(2)
df = DataFrame(a = (ceil.(5 * rand(1000))), g=(rand(1000) .> 0.5))
p1 = df |> @filter(_.g == false) |> @df groupedhist(:a, group=:g, color=1)
p2 = df |> @filter(_.g == true) |> @df groupedhist(:a, group=:g, color=2)
p12 = @df df groupedhist(:a, group=:g, nbins=5)
plot(p1, p12, p2, layout=(1,3), link=:both, legend=:bottomright)
```

![groupedhist](https://user-images.githubusercontent.com/4634605/88113435-167b0680-cbb2-11ea-8207-903280fc54af.png)

**Comment by SteffenPL** [comment]
See also #219

**Comment by SteffenPL** [comment]
An easier example, somehow the groups get mixed up.

```julia
using DataFrames, Random, StatsPlots, Query
df = DataFrame(a = [1,1,1,1,2,1], g= (collect(1:6) .< 5))

6×2 DataFrame
│ Row │ a     │ g    │
│     │ Int64 │ Bool │
├─────┼───────┼──────┤
│ 1   │ 1     │ 1    │
│ 2   │ 1     │ 1    │
│ 3   │ 1     │ 1    │
│ 4   │ 1     │ 1    │
│ 5   │ 2     │ 0    │
│ 6   │ 1     │ 0    │


p1 = df |> @filter(_.g == false) |> @df groupedhist(:a, group=:g, color=1)
p2 = df |> @filter(_.g == true)  |> @df groupedhist(:a, group=:g, color=2)
p12 = @df df groupedhist(:a, group=:g, nbins=5, bar_position = :stack)
plot(p1, p12, p2, layout=(1,3), link=:both, legend=:bottomright)
```
![simpleexample](https://user-images.githubusercontent.com/4634605/88116220-64930880-cbb8-11ea-8d28-dd7ac02c3cb8.png)

**Comment by SteffenPL** [comment]
This commit causes the error: https://github.com/JuliaPlots/StatsPlots.jl/commit/45a132ebfae45604ab8174ce5b305da1598c0198

**Comment by Moelf** [comment]
@SteffenPL great test examples, I tested these on the 0.14.8 and these two test cases are still broken. (with rolled back 45a132e); I recall what got me first working on them was that grouphist won't work with log-y scale + stacking
