### ISSUE TITLE
mismatch between data an bar height in grouped bar chart (log+lin, only in master)

### ISSUE THREAD

**Issue by joergbuchwald** [JuliaPlots/StatsPlots.jl#357]
Hi,
since an update recently, I discovered a serious mismatch between the bar height and the data producing the bars.
Here are some examples:
https://github.com/joergbuchwald/projects/blob/master/temp/logplot.ipynb
In the log plot, all bars do have nearly the same height whereas there should be one order of magnitude in between.
The same holds also for the linear and log plot below. The ticks on the left should match the bar heights (e.g. for 10 and 12)

**Comment by joergbuchwald** [comment]
Updating to julia 1.5 seems to fix the problem.
However, #263 seems to be somehow relevant again: using `log10` instead of `log` requires the `fillrange` attribute to be set again.

**Comment by hendri54** [comment]
I don't think it's just in master. With Julia 1.4.2 (MacOS), Plots 1.5.8, StatsPlots 0.14.7, this simple example gives bars that are taller than 1:

```
julia> using Random, StatsPlots
julia> rng = MersenneTwister(123);
julia> p=groupedbar(["1", "2", "3", "4"], rand(rng, 4, 2))
```

**Comment by joergbuchwald** [comment]
Yes, probably. I haven't seen this.
It worked with 0.14.6, as I remember. The 0.14.7 release is quite new.

**Comment by hendri54** [comment]
Thanks for that pointer - pinning 0.14.6 works for me.

**Comment by BeastyBlacksmith** [comment]
Would be nice, if you can report back, if 0.14.8 solves this issue, when it is released

**Comment by joergbuchwald** [comment]
It doesn't seem to be fixed yet.
(See the above mentioned jupyter notebook for further details).

**Comment by joergbuchwald** [comment]
This looks good! Thank you very much!
