### ISSUE TITLE
ArgumentError: unsupported symbol b passed to label

### ISSUE THREAD

**Issue by HelgavonLichtenstein** [JuliaPlots/StatsPlots.jl#358]
Hello, when I use the example from https://github.com/JuliaPlots/StatsPlots.jl
```
using DataFrames, StatsPlots
df = DataFrame(a = 1:10, b = 10 .* rand(10), c = 10 .* rand(10))
@df df plot(:a, cols(2:3), colour = [:red :blue])
```
I get the error `ArgumentError: unsupported symbol b passed to label`

Does anyone know what I am missing?

**Comment by BeastyBlacksmith** [comment]
Can you try, if https://github.com/JuliaPlots/StatsPlots.jl/pull/359 fixes this issue?

**Comment by HelgavonLichtenstein** [comment]
Sorry, I don't know how to do that. Is it an update? If so, no changes occur.

**Comment by BeastyBlacksmith** [comment]
Try `] add StatsPlots#bbs/df`

**Comment by HelgavonLichtenstein** [comment]
It does not fix the issue :(
