### ISSUE TITLE
Expose sorting options for boxplots (and other plots?)

### ISSUE THREAD

**Issue by nwilleyltk** [JuliaPlots/StatsPlots.jl#409]
By default the boxplot orders a categorical axis alphabetically.  Often times, there is a semantic ordering that makes more sense.  Allowing the user to specify the order for the x-axis would be a meaningful enhancement.

**Comment by sethaxen** [comment]
Probably as simple as providing a `sort` keyword argument (we could provide `by`, similar to `sort`, but this way a user could pass `identity` to avoid sorting entirely).
