### ISSUE TITLE
How to adjust the X-axis order of boxplot with StatsPlots.jl

### ISSUE THREAD

**Issue by ShuhuaGao** [JuliaPlots/StatsPlots.jl#428]
```julia
using Plots, StatsPlots, DataFrames

df = DataFrame(
    id=repeat([3, 17, 21], inner=10),
    value=randn(30)
)

@df df boxplot(string.(:id), :value, fillalpha=0.75, linewidth=1)
```
The result is 

![image](https://user-images.githubusercontent.com/20141984/109322823-b6f28100-788d-11eb-82e1-5cb04b95757d.png)

I want the box to be 3, 17, 21 from left to right.

PS: I have also tried `CategoricalArray` for the `id` column by setting levels to `[3, 17, 21]`, but nothing changed.

**Comment by mkborregaard** [comment]
I've answered on discourse - let's have the discussion there: https://discourse.julialang.org/t/how-to-adjust-the-x-axis-order-of-boxplot-with-statsplots-jl/56065/2?u=mkborregaard

**Comment by cocoa1231** [comment]
I was wondering if there has been any work on implementing something like an order option as discussed in the discourse post? Right now I have to do all my plotting using Seaborn in Python since the order on the x axis always gets changed.
