### ISSUE TITLE
Plotting discrete distributions with non-integer support

### ISSUE THREAD

**Issue by sethaxen** [JuliaPlots/StatsPlots.jl#450]
StatsPlots currently incorrectly assumes all discrete distributions have their support on the integers. This causes distributions with e.g. support on the floating point numbers to error when you plot them. A MWE:

```julia
julia> using StatsPlots, Distributions

julia> plot(Dirac(1.0))  # this is fine

julia> plot(Dirac(0.5))
ERROR: InexactError: Int64(0.5)
Stacktrace:
  [1] Int64
    @ ./float.jl:723 [inlined]
  [2] _broadcast_getindex_evalf
    @ ./broadcast.jl:648 [inlined]
  [3] _broadcast_getindex
    @ ./broadcast.jl:621 [inlined]
  [4] #19
    @ ./broadcast.jl:1098 [inlined]
  [5] ntuple
    @ ./ntuple.jl:49 [inlined]
  [6] copy
    @ ./broadcast.jl:1098 [inlined]
  [7] materialize
    @ ./broadcast.jl:883 [inlined]
  [8] yz_args(dist::Dirac{Float64})
    @ StatsPlots ~/.julia/packages/StatsPlots/ie0L8/src/distributions.jl:25
  [9] macro expansion
    @ ~/.julia/packages/StatsPlots/ie0L8/src/distributions.jl:32 [inlined]
 [10] apply_recipe(plotattributes::AbstractDict{Symbol, Any}, dist::Distribution)
    @ StatsPlots ~/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:282
 [11] _process_userrecipes!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/CirY4/src/user_recipe.jl:36
 [12] recipe_pipeline!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/CirY4/src/RecipesPipeline.jl:70
 [13] _plot!(plt::Plots.Plot, plotattributes::Any, args::Any)
    @ Plots ~/.julia/packages/Plots/FKcum/src/plot.jl:172
 [14] plot(args::Any; kw::Any)
    @ Plots ~/.julia/packages/Plots/FKcum/src/plot.jl:58
 [15] plot(args::Any)
    @ Plots ~/.julia/packages/Plots/FKcum/src/plot.jl:52
 [16] top-level scope
    @ REPL[23]:1
```

This came up in https://github.com/devmotion/InferenceDiagnostics.jl/pull/7. @devmotion [noted](https://github.com/devmotion/InferenceDiagnostics.jl/pull/7#issuecomment-861038830):
> ...the resulting plot is incorrect since StatsPlots incorrectly assumes that discrete distributions are integer-valued (https://github.com/JuliaPlots/StatsPlots.jl/blob/6e65c64fb99ca5148989766092a5432391ab1e3b/src/distributions.jl#L25). This is not correct e.g. for discrete location-scale distributions, Dirac distributions, and `DiscreteNonParametric`.

**Comment by devmotion** [comment]
The main annoyance here is probably that one can't use `support(dist)` since it errors for unbounded distributions: https://github.com/JuliaStats/Distributions.jl/issues/1254

However, one could at least use `support(dist)` for bounded distributions. I also opened an issue in InfiniteArrays if it would be possible to make it more lightweight (it pulls in quite many dependencies), which would allow us to fix and work with unbounded support as well.

**Comment by sethaxen** [comment]
Another challenge is that `support(dist)` dos not necessary produce values that will evaluate to have non-zero probability. e.g.

```julia
julia> d = Binomial(5, 0.5)
Binomial{Float64}(n=5, p=0.5)

julia> d2 = (d - mean(d)) / std(d)
LocationScale{Float64, Discrete, Binomial{Float64}}(
μ: -2.23606797749979
σ: 0.8944271909999159
ρ: Binomial{Float64}(n=5, p=0.5)
)


julia> pdf.(d, support(d))
6-element Vector{Float64}:
 0.03125
 0.15624999999999994
 0.31249999999999994
 0.31249999999999994
 0.15624999999999994
 0.03125

julia> pdf.(d2, support(d2))  # should be the same as above
6-element Vector{Float64}:
 0.03125
 0.0
 0.31249999999999994
 0.31249999999999994
 0.15624999999999994
 0.03125
```

**Comment by devmotion** [comment]
That's a numerical issue, for discrete distributions it is safer to scale with rationals I assume.

**Comment by sethaxen** [comment]
Unfortunately `//` only works for integer arguments, so `(d - mean(d)) // std(d)` and `(d - mean(d)) * (1 // std(d))` don't work due to `std(d)` being a float.

**Comment by devmotion** [comment]
Yes, you have to base the transformation on rationals (as done in InferenceDiagnostics) and not `std` or `mean`.

**Comment by sethaxen** [comment]
Yet we have no control how the user chooses to construct their distribution. Anyways, this particular case seems like something to handle at the Distributions level. Here I think we can safely use `support` here, and if that errors fall back to the old way of doing things (though without the `Int` call).

Though looks like `support(::Dirac)` returns a single-entry `Tuple`, while other discrete distributions return ranges. The only documentation I see on `support` is for `support(::DiscreteNonParametric)` which says that the return value is a sorted `AbstractVector`.

**Comment by devmotion** [comment]
There is no guarantee regarding the return type. For continuous distributions often it is a RealInterval, for discrete distributions often a range, sometimes a vector, and a tuple for Dirac. `minimum` and `maximum` are defined for all of the returned type and the discrete ones are iterable.
