### ISSUE TITLE
Weird messages from StatsPlots.jl in Pluto.jl

### ISSUE THREAD

**Issue by aerdely** [JuliaPlots/StatsPlots.jl#482]
Please check this [issue](https://github.com/fonsp/Pluto.jl/issues/1870)

**Comment by sethaxen** [comment]
I addressed one of the warnings in https://github.com/fonsp/Pluto.jl/issues/1870#issuecomment-1025322869. The other is a duplicate of https://github.com/JuliaPlots/StatsPlots.jl/issues/470

**Comment by sethaxen** [comment]
These should have been fixed by #486 and https://github.com/JuliaPlots/Plots.jl/pull/4123. @aerdely can you verify that they are?

**Comment by aerdely** [comment]
Everything works fine! No more weird messages. Thank you!
