### ISSUE TITLE
Bump version ?

### ISSUE THREAD

**Issue by t-bltg** [JuliaPlots/StatsPlots.jl#484]
Can we please bump a minor or patch version ?
`StatsPlots` is preventing some updates, and this gets in the way for fixing https://github.com/JuliaPlots/Plots.jl/issues/4091.

**Comment by sethaxen** [comment]
Bumped the version and registered: https://github.com/JuliaRegistries/General/pull/53870

**Comment by t-bltg** [comment]
Thanks !
