### ISSUE TITLE
Grouping by multiple variables by @df produces errant output

### ISSUE THREAD

**Issue by cingulate7** [JuliaPlots/StatsPlots.jl#490]
The 'group = (:key1, :key2)' expression in @df does not produce expected output. The following code produces a legend with 4 categories, but eight plot objects instead of four:

    using DataFrames, StatsPlots

    dfa = DataFrame(a = [0, 1, 0, 1, 0, 1, 0, 1],
                   b = [1, 1, 1, 1, 2, 2, 2, 2],
                   dat = randn(8))

    @df dfa boxplot( :dat, group = (:a, :b) )

![](https://aws1.discourse-cdn.com/business5/uploads/julialang/original/3X/5/a/5a21e514907f7fcb966b55a47cf92047785ba212.png)

**Comment by sethaxen** [comment]
The first argument to `boxplot` should be the labels of the individual boxplots that should be plotted. Without that, it uses `eachindex`, and you're plotting one boxplot per data point.

Is this what you want?
```julia
@df dfa boxplot(string.(tuple.(:a, :b)), :dat; group = (:a, :b))
```
![image](https://user-images.githubusercontent.com/8673634/154520877-00be7531-3db4-4a3f-b798-5fa5338b7c2a.png)

**Comment by cingulate7** [comment]
thank you!!!! This has been driving me crazy all week.
