### ISSUE TITLE
errorline! not cycling palette

### ISSUE THREAD

**Issue by alancummings** [JuliaPlots/StatsPlots.jl#523]
If I run the sample code at https://docs.juliaplots.org/latest/generated/statsplots/#ErrorLine the colors do not cycle correctly.

- The first plot is blue (appropriate)
- The second plot is orange (appropriate)
- The 3rd plot is orange again (**NOT** appropriate)

**To reproduce**: I start with a fresh julia REPL  `using StatsPlots` and copy paste the example from the link above

**Additional info**: I modified the example to create a plot with `p = plot()`, then use `errorline!` for all 3 series. In this case **all 3 plots are _orange_**

I am running julia version 1.8.5 in a VSCode type environment (under code-server: https://github.com/coder/code-server) on an AWS amazon linux 2 instance

**Comment by BeastyBlacksmith** [comment]
CC: @CMGreenspon

**Comment by CMGreenspon** [comment]
Okay, it seems like the GR backend changed how it counts the number of primary series. I've implemented a fix to make it explicitly count the number of primary series instead of relying on the GR counter.

**Comment by BeastyBlacksmith** [comment]
Would be good to know on which version of Plots this behaved differently. I don't think it is related to GR

**Comment by alancummings** [comment]
> 

I have Plots v1.38.3 and StatsPlots v0.15.4
