### ISSUE TITLE
Tree plot for Hclust

### ISSUE THREAD

**Issue by kescobo** [JuliaPlots/StatsPlots.jl#73]
I managed to generate what I think are the [beginnings of a recipe](https://gist.github.com/kescobo/799bf484e96a854857cb65f2c5685693) for plotting a tree with `Hclust` types from [`Clustering.jl`](https://github.com/JuliaStats/Clustering.jl):

```julia
using Distances
using Clustering
using StatPlots

include("hclustrecipe.jl")

m = rand(100,10)
dm = pairwise(Distances.Jaccard(), m)

clust = hclust(dm, :average)

plot(hclustplot(clust, true),seriestype=:path, color=:black,
    yaxis=nothing, grid=false, legend=false, xticks=clust.labels)
```

![clustplot](https://user-images.githubusercontent.com/3502975/29618873-796c0454-87e7-11e7-8f45-ecd50c68e2ca.png)

Ultimately, I want to combine this with a heatmap to generate something that looks like this:

<img width="589" alt="screenshot 2017-08-23 09 51 34" src="https://user-images.githubusercontent.com/3502975/29619267-aac614c6-87e8-11e7-85e9-a9b42279c501.png">

Wondering what the next steps are - in other words where should I submit a PR? Do I add it to `Clustering.jl`, or somewhere in this repo?

**Comment by mkborregaard** [comment]
That's very nice! IMHO the best place to have a recipe is always in the directory that defines the Type. That makes for the best dependency structure and ensures that the recipe is updated when the type or interface changes. It's an open question whether Clustering.jl will accept a dep on RecipesBase, though - though it's a safe (very light) dep.

**Comment by kescobo** [comment]
@mkborregaard Got it. So maybe I should open an issue there, and ask whether they'd be willing to accept this? It would still need a lot of work though, and I think I'd need your help to get the combo working (though maybe the combo would go here since it depends on `heatmap()`?)

**Comment by mkborregaard** [comment]
`heatmap` is not a problem. You could start by opening an issue and hear if they'd be willing to accept a PR. I'm happy to help as much as I can.

**Comment by kescobo** [comment]
@mkborregaard Seems like [the answer](https://github.com/JuliaStats/Clustering.jl/issues/90) is no.

So then, is this the best place for it? I'm working on this as part of the development of a package for working with microbiome data. I could just leave it there for now, and move it elsewhere if it seems like it would be more broadly useful.

**Comment by mkborregaard** [comment]
PlotRecipes is the best place for it, I think. There's a lot of functionality for graphs already, and one solution could be to add a general `dendrogram` layout to the `graphplot` recipe that did the dendrogram, and then just let the hclust recipe dispatch to that. If you're not up for that, just try making the pr marked WIP on PlotRecipes (in the misc.jl file) as it is, and we can discuss from there.

**Comment by mkborregaard** [comment]
Oh, sorry, I just read your email again. Right now it would probably be even nicer to just keep it in your package. You could develop it an play with it, and it could always go to PlotRecipes later if broadly useful. Still willing to help getting the recipe right if you post a link.

**Comment by srgk26** [comment]
#214

**Comment by srgk26** [comment]
**WIP: clustered heatmap aka clustermap #214**
