### ISSUE TITLE
groupedbar with labels

### ISSUE THREAD

**Issue by cstjean** [JuliaPlots/StatsPlots.jl#90]
```julia
bench_seq = b_learn
gbar = groupedbar(rand(5,3), labels=["a", "b", "c"])
```

![screen shot 2017-09-09 at 12 15 45](https://user-images.githubusercontent.com/8622776/30241813-b09a7036-9558-11e7-864c-13bfc8c8bb4f.png)

Broken at least on `plotlyjs` and `pyplot`

**Comment by piever** [comment]
Attributes across series have to be a row vector:
`groupedbar(rand(5,3), labels=["a" "b" "c"])`

We should really write this more prominently in the documentation, the issue keeps coming up...

**Comment by mkborregaard** [comment]
I agree this keeps coming up. It actually is written quite clearly in the docs ("Columns are series" here https://juliaplots.github.io/input_data/ ) - the question would be where to put it to make sure all users would see it?
