### ISSUE TITLE
KernelDensity.jl plots are not working

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/StatsPlots.jl#92]
```julia
using KernelDensity
using StatPlots; pyplot()

plot(kde(randn(1000,2)))
```
>PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, kw)) <class 'TypeError'>
TypeError('Length of x must be number of columns in z.',)
  File "/usr/lib/python3.6/site-packages/matplotlib/__init__.py", line 1898, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5825, in contour
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/matplotlib/contour.py", line 864, in __init__
    self._process_args(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/matplotlib/contour.py", line 1429, in _process_args
    x, y, z = self._contour_args(args, kwargs)
  File "/usr/lib/python3.6/site-packages/matplotlib/contour.py", line 1508, in _contour_args
    x, y, z = self._check_xyz(args[:3], kwargs)
  File "/usr/lib/python3.6/site-packages/matplotlib/contour.py", line 1555, in _check_xyz
    raise TypeError("Length of x must be number of columns in z.")

**Comment by piever** [comment]
I'm afraid that there is no recipe for 2D density plots, so you'd need to do something like:

```julia
s = kde(randn(1000,2))
heatmap(s.x, s.y, s.density)
```

to get what you want.

We were planning to add one such recipe here but nobody has made a PR yet.

**Comment by juliohm** [comment]
@piever what is the recipe at StatPlots.jl for? https://github.com/JuliaPlots/StatPlots.jl/blob/master/src/StatPlots.jl#L18

**Comment by piever** [comment]
Ups, I was blind. That recipe is only be meant to be used for plots representing a 2D distribution:

```julia
heatmap(kde(randn(1000,2)))
contourf(kde(randn(1000,2)))
surface(kde(randn(1000,2)))
```

When you try `plot(kde(randn(1000,2)))` it gets translated to

```julia
s = kde(randn(1000,2))
plot(s.x, s.y, s.density)
```

which will not work as a plot command.

What's the issue with the snippet of code I provided above, except being a bit annoying to type all the time?

**Comment by piever** [comment]
What I meant as a future plan is to have something like `density(x, y)` being translated to `contourf(kde([x y]))`. It'd be consistent with `density(x)` for univariate distributions which is implemented already.

**Comment by piever** [comment]
Actually you were right in that `plot(kde(randn(1000,2)))` gets translated to `contour(kde(randn(1000,2)))` that is to say:

```julia
s = kde(randn(1000,2))
contour(s.x, s.y, s.density)
```

At least on my system that gives a non-deterministic bug (with PyPlot, but also GR behaves strangely) and every once in a while I get the same error as you. That's however a problem with contour plots (and heatmap/surface plots), not with the kernel density recipe as far as I can tell.

**Comment by piever** [comment]
Let me know if that solves it so that I can update the recipe at https://github.com/JuliaPlots/StatPlots.jl/blob/master/src/StatPlots.jl#L18

**Comment by juliohm** [comment]
It works nicely @piever , could you please go ahead and fix the order? Thank you very much.
