### ISSUE TITLE
"Missing data of type Any is not supported" for df macro.

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/StatsPlots.jl#94]
Consider the following piece of code:
```julia
using StatPlots, DataFrames

df_any = DataFrame(Any, 0, 1)
df_array_any = DataFrame(Array{Any}(0, 1))

for i in 1:10
    push!(df_any, rand())
    push!(df_array_any, rand())
end

@df df_any plot(:x1) # Error: "Missing data of type Any is not supported"
@df df_array_any plot(:x1) # works
```
I'm not sure if this is related to StatPlots or DataFrames, if this is expected or an issue. I was just a little surprised.
cc: @piever

**Comment by piever** [comment]
There is an embarrassing mistake [here](https://github.com/JuliaPlots/StatPlots.jl/blob/master/src/df.jl#L77), I somehow got convinced that the second argument doesn't get evaluated if the DataValue is not null, which is not the case: I'll patch as soon as possible.
